### PR TITLE
adreno: update blob from 17.1.2.A.0.314

### PR DESCRIPTION
**Pull request by OmarEinea1**
Merge "adreno: update blob from 17.1.2.A.0.314" into "TheLoonyBin/proprietary_vendor_sony"

### CODE REVIEW

**Comment by PRJosh** [comment]
There is a missing qcom-common commit there no?

**Comment by OmarEinea1** [comment]
Which commit are you referring to exactly?

**Comment by PRJosh** [comment]
https://github.com/TheMuppets/proprietary_vendor_sony/commit/d41a2d90c873ed797edb0f1a919d1a0bf18c2fb5

Josue Rivera

**Comment by OmarEinea1** [comment]
Oh ok will pull it and create a new pull request.

**Pull request closed without merging**
